### ISSUE TITLE
Desc is needed to clone

### ISSUE THREAD

**Issue by RoHit4100** [JehanKandy/GYM-Management-System#234]
-There is no desc for cloning the project..
-I just suggest that desc needs to add for the users to know how to clone the project

**Comment by JehanKandy** [comment]
it's my organization i just cloning :)

**Comment by RoHit4100** [comment]
> * do you mean this https://github.com/The-Lion-s-Crew/GYM-Management-System

No I mean u have to add some description to know the others peoples how to clone this project from github to their Machine....
If Want that I can contribute to your project

**Comment by JehanKandy** [comment]
ok friend thank you for informing me about that
today I can add it,
because I complete this project today

**Comment by RoHit4100** [comment]
Congratulations 🎊

**Comment by JehanKandy** [comment]
Thanks bro Today I can End the project
